### ISSUE TITLE
Newer decorator versions do not install on OSX

### ISSUE THREAD

**Issue by npavlovikj** [conda-forge/decorator-feedstock#5]
Hi,

I tried installing `decorator` on OSX, and for every version **>=4.3.0** I am getting the following error:
```
Executing transaction: failed
ERROR conda.core.link:_execute(568): An error occurred while installing package 'conda-forge::decorator-4.4.0-py_0'.
OSError(2, 'No such file or directory')
Attempting to roll back.
Rolling back transaction: done
CondaMultiError: [Errno 2] No such file or directory
```
for every Python version (2,7, >=3).

I looked at this error a bit, and I believe the main reason is that `python3.6` (or the respective versions) is not found in the `/bin/` directory of the environment.

On the other hand, `decorator` 4.2.1 and below, installed from `conda-forge` work fine on OSX.

Also, this issue with the newet `decocrator` versions doesn't occur on Linux.

I haven't had chance to investigte this further, but I just wanted to let you know.

Thank you,
Natasha

**Comment by ocefpaf** [comment]
I do not have a macOS to test but `decorator 4.4.0` is `noarch` and it worked for me on Linux. Can you please fill the required information in the issue template to help us debug this? (All the stuff you deleted when you opened the issue.)

**Comment by scopatz** [comment]
Maybe do a build number bump and rerender to fix this?

**Comment by ocefpaf** [comment]
> Maybe do a build number bump and rerender to fix this?

Can you confirm the problem on your macOS? Everything is working on my Windows and Linux machine, it is more likely that there is something wrong with the environment, that is why I request the issue template data.

**Comment by scopatz** [comment]
Sorry I don't have the time to do that :wink:

**Comment by jakirkham** [comment]
We're seeing this in [the Docker image build]( https://circleci.com/gh/conda-forge/docker-images/224 ) as well. Maybe this is another case of having issues with Conda installing noarch packages, which are its dependencies? If so, maybe we should convert this back to arch and pull the noarch packages.

**Comment by ocefpaf** [comment]
I just upgraded to `conda 4.7.4`, like in the docker image, and it still works for me locally in a new env. Not sure if making it `arch` again is the solution here.

**Comment by jakirkham** [comment]
The Docker image build also upgrades to the latest Conda. So I don't think that is the fix.

**Comment by npavlovikj** [comment]
I am sorry for the lack of information @ocefpaf . I was encountering this issue only on OSX, but it worked fine on Linux.
I did `conda update --all` on my OSX machine, and `decorator` works fine now. I know I had `conda 4.6.14` earlier, but I can not recall what other packages got updated that must have fixed the issue. I can replicate the error with `conda 4.5.11`, but I guess that is outdated version now. I will try to roll-back my earlier conda env and will let you know if I replicate the error.

**Comment by ocefpaf** [comment]
>  I will try to roll-back my earlier conda env and will let you know if replicate the error.

Thanks!

**Comment by jakirkham** [comment]
Starting with Miniconda 4.6.14 also seems to avoid this issue in the Docker image build. ( https://github.com/conda-forge/docker-images/pull/96 )

**Comment by ocefpaf** [comment]
@npavlovikj closing this b/c I believe it was fixed. Please reopen if you are still experiencing this.
